# Dataset Paths
data:
  raw: "data/raw/telco_churn.csv"
  processed: "data/processed/telco_churn_processed.csv"
  predictions: "data/predictions/churn_predictions.csv"

# Model Parameters
models:
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
    class_weight: "balanced"

  xgboost:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    random_state: 42
    eval_metric: "logloss"

  catboost:
    iterations: 100
    depth: 5
    learning_rate: 0.1
    random_state: 42
    verbose: False

# Feature Lists
features:
  numerical:
    - tenure
    - MonthlyCharges
    - TotalCharges

  categorical:
    - gender
    - Contract
    - PaymentMethod
    - InternetService
    - OnlineSecurity
    - OnlineBackup
    - DeviceProtection
    - TechSupport
    - StreamingTV
    - StreamingMovies
    - Partner
    - Dependents
    - PhoneService
    - MultipleLines
    - PaperlessBilling

# Target Variable
target: Churn

# MLflow Settings
mlflow:
  experiment_name: "telco_churn_prediction"
  tracking_uri: "mlruns"

# Training Settings
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5